#!/usr/bin/env python3
"""Generate the pipeline statistics note and the Kanban board from tracker frontmatter.

Outputs (overwritten on every run, never edit them by hand):
- _Pipeline-Stats.md: conversion funnel, conversion by track, response rate by
  source, and rejection reasons.
- Pipeline-Board.md: an obsidian-kanban board with one lane per stage. It is a
  view: moving a card does not change the tracker, so change `stage` instead.

The funnel counts an application at every stage up to the furthest one it
reached: max(stage, reached), where `reached` records how far a rejected,
withdrawn, or ghosted application got (see _Application-Schema.md).

Usage:
    pipeline_views.py            # write both notes
    pipeline_views.py --check    # print the stats to stdout, write nothing
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

from tracker_frontmatter import read_frontmatter, read_list

PIPELINE = Path(__file__).resolve().parent
TRACKER_DIRS = ("Active", "Archive")
PROGRESS = ["sourced", "applied", "recruiter", "OA", "phone", "onsite", "offer"]
TERMINAL = ["rejected", "withdrawn", "ghosted"]
STAGES = PROGRESS + TERMINAL


@dataclass
class App:
    name: str
    company: str
    stage: str
    reached: str
    tracks: list[str]
    source: str
    rejection_reason: str

    @property
    def furthest(self) -> int:
        ranks = [PROGRESS.index(s) for s in (self.stage, self.reached) if s in PROGRESS]
        return max(ranks, default=PROGRESS.index("applied"))

    @property
    def responded(self) -> bool:
        """Any reply at all: a rejection counts; silence and a withdrawal without a reply do not."""
        return self.stage == "rejected" or self.furthest > PROGRESS.index("applied")


def load(root: Path = PIPELINE) -> list[App]:
    apps = []
    for d in TRACKER_DIRS:
        for p in sorted((root / d).rglob("*.md")):
            text = p.read_text(errors="ignore")
            fm = read_frontmatter(text)
            if not fm.get("company") or not fm.get("stage"):
                continue
            tracks = read_list(text, "track")
            apps.append(App(p.stem, fm["company"], fm["stage"], fm.get("reached", ""), tracks or ["unassigned"],
                            fm.get("source", "") or "unknown", fm.get("rejection_reason", "")))
    return apps


def pct(n: int, d: int) -> str:
    return f"{100 * n / d:.0f}%" if d else "-"


def stats(apps: list[App]) -> str:
    total = len(apps)
    lines = ["---", "type: playbook", "status: draft", "---", "", "# Pipeline statistics", "",
             "Generated by `pipeline_views.py` from tracker frontmatter; it is overwritten on every run.", "",
             f"Applications: {total}.", "", "## Conversion funnel", "",
             "An application counts at every stage up to the furthest one it reached.", "",
             "| Stage | Reached | Of all | From previous stage |", "| :--- | ---: | ---: | ---: |"]
    prev = None
    for i, s in enumerate(PROGRESS[1:], start=1):
        n = sum(1 for a in apps if a.furthest >= i)
        lines.append(f"| {s} | {n} | {pct(n, total)} | {pct(n, prev) if prev is not None else '-'} |")
        prev = n

    lines += ["", "## Current stage", "", "| Stage | Applications |", "| :--- | ---: |"]
    current = Counter(a.stage for a in apps)
    lines += [f"| {s} | {current[s]} |" for s in STAGES if current[s]]
    lines += [f"| {s} (not a canonical stage) | {n} |" for s, n in current.items() if s not in STAGES]

    lines += ["", "## By track", "", "| Track | Applications | Got a response | Reached phone or later |", "| :--- | ---: | ---: | ---: |"]
    by_track: dict[str, list[App]] = defaultdict(list)
    for a in apps:
        for t in a.tracks:
            by_track[t].append(a)
    for t, group in sorted(by_track.items(), key=lambda kv: -len(kv[1])):
        resp = sum(a.responded for a in group)
        deep = sum(a.furthest >= PROGRESS.index("phone") for a in group)
        lines.append(f"| {t} | {len(group)} | {resp} ({pct(resp, len(group))}) | {deep} ({pct(deep, len(group))}) |")

    lines += ["", "## Response rate by source", "", "| Source | Applications | Got a response | Rate |", "| :--- | ---: | ---: | ---: |"]
    by_source: dict[str, list[App]] = defaultdict(list)
    for a in apps:
        by_source[a.source].append(a)
    for s, group in sorted(by_source.items(), key=lambda kv: -len(kv[1])):
        resp = sum(a.responded for a in group)
        lines.append(f"| {s} | {len(group)} | {resp} | {pct(resp, len(group))} |")

    rejected = [a for a in apps if a.stage == "rejected"]
    lines += ["", "## Rejection reasons", ""]
    if rejected:
        lines += ["| Application | Reached | Reason |", "| :--- | :--- | :--- |"]
        lines += [f"| [[{a.name}]] | {PROGRESS[a.furthest]} | {(a.rejection_reason or 'not recorded').replace('|', '/')} |"
                  for a in sorted(rejected, key=lambda a: a.company.lower())]
    else:
        lines.append("None.")
    return "\n".join(lines) + "\n"


def board(apps: list[App]) -> str:
    lines = ["---", "", "kanban-plugin: board", "", "---", "",
             "<!-- Generated by pipeline_views.py; change `stage` in the tracker, not the card position. -->", ""]
    for s in STAGES:
        lines += [f"## {s}", ""]
        lines += [f"- [ ] [[{a.name}]]" for a in sorted(apps, key=lambda a: a.company.lower()) if a.stage == s]
        lines.append("")
    lines += ["", "%% kanban:settings", "```", '{"kanban-plugin":"board","list-collapse":[false,false,false,false,false,false,false,true,true,true]}', "```", "%%", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", type=Path, default=PIPELINE)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    apps = load(args.root)
    text = stats(apps)
    if args.check:
        print(text)
        return 0
    (args.root / "_Pipeline-Stats.md").write_text(text)
    (args.root / "Pipeline-Board.md").write_text(board(apps))
    print(f"pipeline_views: {len(apps)} applications -> _Pipeline-Stats.md, Pipeline-Board.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
